Adds ability to specify the app-name and instance-name in the docker-build command

diff --git a/bin/docker-build b/bin/docker-build
--- a/bin/docker-build
+++ b/bin/docker-build
@@ -7,6 +7,55 @@ APP=$(basename $PWD)
 INSTANCE=$(git rev-parse --abbrev-ref HEAD)
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
+usage() {
+    cat <<EOF
+Usage: $0 [-a|--app-name <name>] [-i|--instance-name <name>]
+
+    Build the Docker container.
+
+    -a | --app-name <name>
+        The name of the app. Defaults to the name of the project directory
+
+    -i | --instance-name <name>
+        The name of the test instance. Defaults to the branch name
+
+    -h | --help
+        This help message
+EOF
+    exit 1;
+}
+
+while (( "$#" )); do
+  [[ $1 == --*=* ]] && set -- "${1%%=*}" "${1#*=}" "${@:2}"
+  case "$1" in
+    -a|--app-name)
+      APP=$2
+      shift 2
+      ;;
+    -i|--instance-name)
+      INSTANCE=$2
+      shift 2
+      ;;
+    -h|--help)
+      usage
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      usage
+      ;;
+  esac
+done
+
+echo "Building container with variables:"
+echo "  APP_NAME: $APP"
+echo "  INSTANCE_NAME: $INSTANCE"
+echo "  BRANCH_NAME: $BRANCH"
+echo "  RELEASE: $RELEASE"
+
 gatsby build
 
 docker build \
